root: true
env:
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: true
  sourceType: module
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-type-checked'
  - prettier
rules:
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/unbound-method': 'off'
  '@typescript-eslint/no-unsafe-assignment': 'off'
  '@typescript-eslint/no-unsafe-member-access': 'off'
  '@typescript-eslint/no-unsafe-return': 'off'
  '@typescript-eslint/restrict-template-expressions':
    - error
    - allowAny: true
overrides:
  - files: '**/*.test.ts'
    plugins:
      - jest
    extends:
      - 'plugin:jest/recommended'
      - 'plugin:jest/style'
