language: node_js
node_js:
  - "8.11.3"
branches:
  only:
  - master
install:
  - npm install -g firebase-tools
  - cd ./frontend && npm install && cd ..
script:
  - cd ./frontend && npm run build && cd ..
after_success:
  - firebase deploy --only hosting --token "$FIREBASE_TOKEN" --project "$FIREBASE_PROJECT"
