language: node_js
node_js:
  - "8.11.3"
branches:
  only:
    - master
stages:
  - name: staging
    if: branch = master AND type != pull_request
jobs:
  include:
    - stage: staging
      install:
        - npm install -g firebase-tools
        - cd ./functions && npm install && cd ..
        - cd ./frontend && npm install && cd ..
      script:
        - cd ./frontend && npm run build && cd ..
        - cd ./functions && npm run build && cd ..
      after_success:
        - firebase deploy --token "$FIREBASE_TOKEN" --project "$FIREBASE_PROJECT"
