language: node_js
node_js:
  - "node"
script:
  -
after_success:
  - npm install --prefix ./functions
  - npm install --prefix ./frontend
deploy:
  # Development deployment
  - provider: firebase
    project: $FIREBASE_DEV_PROJECT
    skip_cleanup: true
    token:
      secure: $FIREBASE_DEV_TOKEN
    on:
      all_branches: true
  # Staging deployment
  - provider: firebase
    project: $FIREBASE_STAGING_PROJECT
    skip_cleanup: true
    token:
      secure: $FIREBASE_STAGING_TOKEN