language: node_js
node_js:
  - "node"
script:
  -
after_success:
  - npm install --prefix ./functions
deploy:
  provider: firebase
  project: $FIREBASE_PROJECT
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN