#
# sri sri guru gauranga jayatah
#

name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - project: frontend
            node: 10
          - project: functions
            node: 8
          - project: CRP
            node: 10
          - project: cli
            node: 10
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Cache NPM modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: node-${{ matrix.node }}-${{ runner.os }}-${{ matrix.project }}-${{ hashFiles(format('{0}/package-lock.json', matrix.project)) }}
          restore-keys: |
            node-${{ matrix.node }}-${{ runner.os }}-

      - run: npm ci
        working-directory: ${{ matrix.project }}
      - run: npm run lint --if-present
        working-directory: ${{ matrix.project }}
      - run: npm run build --if-present
        working-directory: ${{ matrix.project }}
      - run: npm run test --if-present -- --ci
        working-directory: ${{ matrix.project }}

  create_deployment:
    name: Create deployment
    needs: build
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'deploy:staging')
    steps:
      - name: Create deployment
        uses: maxkomarychev/oction-create-deployment@master
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: ${{ github.head_ref }}
          environment: staging
          required_contexts: <<EMPTY>>
          description: Deploying PR#${{ github.event.number }} from ${{ github.workflow }}
