#
# sri sri guru gauranga jayatah
#

name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and test (${{ matrix.project }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [frontend, functions, gas, cli]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: ${{ matrix.project }}/package.json
          cache: 'npm'
          cache-dependency-path: ${{ matrix.project }}/package-lock.json

      - run: npm ci
        working-directory: ${{ matrix.project }}
      # prettier should be called after installing dependencies so that proper version be picked
      - run: npx prettier --check .
        working-directory: ${{ matrix.project }}
      - run: npm run lint --if-present -- --no-fix
        working-directory: ${{ matrix.project }}
      - run: npm run build --if-present
        working-directory: ${{ matrix.project }}
      - run: npm run test --if-present -- --ci
        working-directory: ${{ matrix.project }}

  create_deployment:
    name: Create deployment
    needs: build
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'deploy:staging')
    steps:
      - name: Create deployment
        uses: maxkomarychev/oction-create-deployment@v0.7.1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: ${{ github.head_ref }}
          environment: staging
          required_contexts: <<EMPTY>>
          description: Deploying PR#${{ github.event.number }} from ${{ github.workflow }}
