#
# sri sri guru gauranga jayatah
#

name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  changes:
    name: Detect changes in sub-projects
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.filter.outputs.changes }}
    steps:
      # Checkout to use filters from file
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: .github/path-filters.yml

  build:
    name: Build and test (${{ matrix.project }})
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      matrix:
        project: ${{ fromJSON(needs.changes.outputs.projects) }}
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: ${{ matrix.project }}/package.json
          cache: 'npm'
          cache-dependency-path: ${{ matrix.project }}/package-lock.json

      - run: npm ci
      # prettier should be called after installing dependencies so that proper version be picked
      - run: npx prettier --check .
      - run: npm run lint --if-present -- --no-fix
      - run: npm run build --if-present
      - run: npm run test --if-present -- --ci
