name: Continuous Integration
# This workflow is triggered on pushes to the repository.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [frontend, functions]
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - run: |
          cd ${{ matrix.project }}
          npm ci
          npm run lint --if-present
          npm run build --if-present
          npm test --if-present
        env:
          CI: true
