#
# sri sri guru gauranga jayatah
#

name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - project: frontend
            node: 10
          - project: functions
            node: 8
          - project: CRP
            node: 10
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
        working-directory: ${{ matrix.project }}
      - run: npm run lint --if-present
        working-directory: ${{ matrix.project }}
      - run: npm run build --if-present
        working-directory: ${{ matrix.project }}
      - run: npm run test --if-present -- --ci
        working-directory: ${{ matrix.project }}
