#
# sri sri guru gauranga jayatah
#

name: Continuous Integration
on: pull_request

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [frontend, functions, CRP]
    env:
      CI: true
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - run: npm ci
        working-directory: ${{ matrix.project }}
      - run: npm run lint --if-present
        working-directory: ${{ matrix.project }}
      - run: npm run build --if-present
        working-directory: ${{ matrix.project }}
      - run: npm run test --if-present
        working-directory: ${{ matrix.project }}
