#
# sri sri guru gauranga jayatah
#

name: Continuous Integration
on:
  pull_request:

jobs:
  changes:
    name: Detect changes in sub-projects
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.filter.outputs.changes }}
    steps:
      # Checkout to use filters from file
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: .github/path-filters.yml

  build:
    name: Build and test
    runs-on: ubuntu-latest
    needs: changes
    # Run only if something was changed in the defiled path filters
    if: needs.changes.outputs.projects != '[]'
    strategy:
      matrix:
        project: ${{ fromJSON(needs.changes.outputs.projects) }}
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ${{ matrix.project }}/package.json
          cache: 'npm'
          cache-dependency-path: ${{ matrix.project }}/package-lock.json

      - run: npm ci
      # prettier should be called after installing dependencies so that proper version be picked
      - run: npx prettier --check .
      - run: npm run lint --if-present -- --no-fix
      - run: npm run build --if-present
      - run: npm run test --if-present -- --ci

  # Summary check depends on the matrix job, runs always and fails if any of the matrix jobs fails
  # https://emmer.dev/blog/skippable-github-status-checks-aren-t-really-required/
  # https://github.com/orgs/community/discussions/26822#discussioncomment-3305794
  check:
    name: Summary check
    if: always()
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
