#
# sri sri guru gauranga jayatah
#

name: Create Deployment
on:
  repository_dispatch:
    types: [deploy-command]

jobs:
  create_deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: maxkomarychev/oction-create-deployment@master
        id: create_deployment
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: ${{ github.event.client_payload.pull_request.head.sha }}
          environment: staging
          state: pending
          description: "From Pull Request"
      - name: Print outputs
        run: |
          echo Id is ${{ steps.create_deployment.outputs.id }}
          echo Number is ${{ steps.create_deployment.outputs.number }}
