#
# sri sri guru gauranga jayatah
#

name: Production Deployment
on:
  push:
    branches:
      - production

jobs:
  create-deployment:
    name: Create deployment
    runs-on: ubuntu-latest
    steps:
      - name: Create deployment
        uses: kamaz/deploy-action@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          environment: production
