#
# sri sri guru gauranga jayatah
#

name: Production Deployment
on:
  push:
    branches:
      - master

jobs:
  create-deployment:
    name: Create deployment
    runs-on: ubuntu-latest
    steps:
      - name: Wait for other check suites to complete
        uses: jitterbit/await-check-suites@v1
        with:
          timeoutSeconds: 600
          onlyFirstCheckSuite: true
      - name: Create deployment
        uses: maxkomarychev/oction-create-deployment@master
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: ${{ github.ref }}
          environment: production
          required_contexts: <<EMPTY>>
