#
# sri sri guru gauranga jayatah
#

name: Pull Request Deployment
on:
  pull_request:
    types: [labeled]

jobs:
  create-deployment:
    name: Create deployment
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'deploy:staging')
    steps:
      - name: Create deployment
        uses: maxkomarychev/oction-create-deployment@0.7.1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: ${{ github.head_ref }}
          environment: staging
          required_contexts: <<EMPTY>>
          description: Deploying PR#${{ github.event.number }} from ${{ github.workflow }}
