#
# sri sri guru gauranga jayatah
#

name: Pull Request Deployment
on:
  pull_request:
    types: [labeled]
  workflow_dispatch:

jobs:
  deployment:
    name: Deployment
    if: contains( github.event.pull_request.labels.*.name, 'deploy:staging')
    uses: ./.github/workflows/deployment.yml
    with:
      environment: staging
