#
# sri sri guru gauranga jayatah
#

name: Pull Request Deployment
on:
  pull_request:
    types: [labeled]

jobs:
  create-deployment:
    name: Create deployment
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'deploy')
    steps:
      - name: Create deployment
        uses: maxkomarychev/oction-create-deployment@master
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: ${{ github.head_ref }}
          environment: staging
          required_contexts: <<EMPTY>>
          state: pending
