#
# sri sri guru gauranga jayatah
#

name: Production Deployment
on:
  push:
    branches:
      - production
      - test
  workflow_dispatch:

jobs:
  deployment:
    name: Deployment
    uses: ./.github/workflows/deployment.yml
    with:
      environment: production
    secrets: inherit
  tag:
    name: Tag
    needs: deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create tag
        run: |
          DATE=$(date +'%Y-%m-%d')
          git tag $DATE
          git push origin $DATE
