#
# sri sri guru gauranga jayatah
#

name: Production Deployment
on:
  push:
    branches:
      - master

jobs:
  create-deployment:
    name: Create deployment
    runs-on: ubuntu-latest
    steps:
      - name: Wait for other check suites to complete
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build
          timeoutSeconds: 300
          intervalSeconds: 30

      - name: Create deployment
        uses: maxkomarychev/oction-create-deployment@master
        if: steps.wait-for-build.outputs.conclusion == 'success'
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: ${{ github.ref }}
          environment: production
          required_contexts: <<EMPTY>>
