#
# sri sri guru gauranga jayatah
#

name: Pull Request Deployment
on:
  issue_comment:
    types: [created]

jobs:
  create-deployment:
    name: Create deployment
    runs-on: ubuntu-latest
    steps:
      - name: Create deployment
        uses: alexjurkiewicz/pr-comment-github-deployment@master
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
