#
# sri sri guru gauranga jayatah
#

name: Production Deployment
on:
  push:
    branches:
      - production

jobs:
  create-deployment:
    name: Create deployment
    runs-on: ubuntu-latest
    steps:
      - name: Create deployment
        uses: maxkomarychev/oction-create-deployment@v0.7.1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: ${{ github.ref }}
          environment: production
          required_contexts: <<EMPTY>>
