#
# sri sri guru gauranga jayatah
#

name: PR Deployment

on:
  pull_request:
    types: [labeled]

jobs:
  deploy:
    if: startsWith(github.event.label.name, 'deploy-')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.pull_request.labels }}
          echo ${{ github.event.label.name }}
          echo ${{ github.event.pull_request.label.name }}
